# Generated by Django 4.1.4 on 2022-12-31 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_subscribedusers_delete_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribedUsers',
            new_name='Newsletter',
        ),
    ]
