# Generated by Django 4.1.4 on 2022-12-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_rename_subscribedusers_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
