# Generated by Django 4.1.4 on 2022-12-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_newsletter_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='content',
        ),
    ]
