# Generated by Django 4.1.4 on 2022-12-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paypal_email',
            field=models.EmailField(max_length=254),
        ),
    ]
