# Generated by Django 4.1.4 on 2022-12-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_vendor',
        ),
    ]
